### ISSUE TITLE
[Korekto][Daily] Votre note actuelle : 3/13

### ISSUE THREAD

**Issue by korekto-agent** [WarningImHack3r/web_app_spring_training#1]
# Exercice commencé
Votre note est de **3**/13.  

## Détail
* Part 1 - Compilation & Tests: 2/2
* Part 2 - CI: 1/1
* Part 3 - HTTP server API: 0/4
    * Fail to call server: No content to map due to end-of-input
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 0]

* Part 4 - Instance-Id header: 0/2
    * Fail to call server: No content to map due to end-of-input
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 0]

* Part 5 - Database persistence: 0/4
    * Expected to find 5 todos inserted in table `public.todo`, but found: 0

*Analyse effectuée à 2021-12-08T08:34:40.188292300Z.*

**Comment by WarningImHack3r** [comment]
Fixed.
